python3 -m venv airflow_env
[0][root@(pgadmin4_oat_blue_1):/home/cloud-user/apache_airflow-2.10.4]
$ source airflow_env/bin/activate
(airflow_env) [0][root@(pgadmin4_oat_blue_1):/home/cloud-user/apache_airflow-2.10.4]
$ pip install -e .
Obtaining file:///home/cloud-user/apache_airflow-2.10.4
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/cloud-user/apache_airflow-2.10.4/airflow_env/bin/python3 /tmp/pip-standalone-pip-9arjji4k/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zbmon_nt/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- GitPython==3.1.43 gitdb==4.0.11 hatchling==1.26.3 packaging==24.2 pathspec==0.12.1 pluggy==1.5.0 smmap==5.0.1 'tomli==2.2.1; python_version < '"'"'3.11'"'"'' trove-classifiers==2024.10.21.16
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7964e003a0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/gitpython/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7964e00670>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/gitpython/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7965050c10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/gitpython/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7965050a60>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/gitpython/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7964e00940>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/gitpython/
  ERROR: Could not find a version that satisfies the requirement GitPython==3.1.43 (from versions: none)
  ERROR: No matching distribution found for GitPython==3.1.43
  ----------------------------------------
WARNING: Discarding file:///home/cloud-user/apache_airflow-2.10.4. Command errored out with exit status 1: /home/cloud-user/apache_airflow-2.10.4/airflow_env/bin/python3 /tmp/pip-standalone-pip-9arjji4k/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zbmon_nt/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- GitPython==3.1.43 gitdb==4.0.11 hatchling==1.26.3 packaging==24.2 pathspec==0.12.1 pluggy==1.5.0 smmap==5.0.1 'tomli==2.2.1; python_version < '"'"'3.11'"'"'' trove-classifiers==2024.10.21.16 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/cloud-user/apache_airflow-2.10.4/airflow_env/bin/python3 /tmp/pip-standalone-pip-9arjji4k/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zbmon_nt/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- GitPython==3.1.43 gitdb==4.0.11 hatchling==1.26.3 packaging==24.2 pathspec==0.12.1 pluggy==1.5.0 smmap==5.0.1 'tomli==2.2.1; python_version < '"'"'3.11'"'"'' trove-classifiers==2024.10.21.16 Check the logs for full command output.
